### ISSUE TITLE
[Issue] KFoldCrossValidation does not seem to properly support all platforms

### ISSUE THREAD

**Issue by ShadowTemplate** [stelong/GPErks#25]
It looks like there are issues with multi-threading on non-Linux platforms.
We have to check everything is ok also on Windows and MacOS with M1 processors.

**Comment by stelong** [comment]
Issue was closed by [this](https://github.com/stelong/GPErks/commit/6d5fea77e00b4986ddf3a323bddac13b0a8a0c1f) commit. To make `KFoldCrossValidation` function Windows-compatible, multiprocessing example code needed to be wrapped with an if-clause.
